image: maven:3.6.0-jdk-8-alpine

stages:
    - build
    - run
    
build:
    stage: build
    script:
        - mvn compile
        - mvn package
        
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths: 
        - target
        when: on_success
        
run:
    stage: run
    script:
    - java -jar ./target/Money-1.0-SNAPSHOT.jar
    dependencies:
    - build
